### PR TITLE
Surface conflicts due to missing caught exceptions

### PR DESCRIPTION
**Pull request by aldexis**
## Before this PR
When a class is being loaded, it goes through a [verification step](https://docs.oracle.com/javase/specs/jvms/se23/html/jvms-4.html#jvms-4.10), which validates the class is structured properly.

Among [other things](https://docs.oracle.com/javase/specs/jvms/se23/html/jvms-4.html#jvms-4.9.2), it will attempt to load (though not necessarily verify) all of the caught exceptions:
```
Each class mentioned in a catch_type item of the exception_table array of the method's Code_attribute structure must be Throwable or a subclass of Throwable.
```

We are currently not checking the exceptions caught within a method actually exist.

## After this PR

==COMMIT_MSG==
Surface conflicts due to missing caught exceptions
==COMMIT_MSG==

### CODE REVIEW

File: abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/conflict/ClassDependency.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+import java.util.List;
+import org.immutables.value.Value;
+
+/**
+ * Represents a dependency between a method and a class it directly references (e.g. in caught exceptions),
+ * used in Conflict when reporting problems.
+ */
+@Value.Immutable
+@JsonSerialize(as = ImmutableMethodDependency.class)
+public interface ClassDependency extends Dependency {
```
Comment (aldexis) [inline abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/conflict/ClassDependency.java:33]: Added a new dependency type to surface in conflicts, since we would currently only be able to report dependencies of a method to another method or field, whereas this is a dependency of a method to a class itself

File: abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/reference/ClassReference.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.palantir.abi.checker.datamodel.reference;
+
+import com.fasterxml.jackson.annotation.JsonValue;
+import com.palantir.abi.checker.datamodel.types.ClassTypeDescriptor;
+
+public record ClassReference(ClassTypeDescriptor clazz) implements Reference {
```
Comment (aldexis) [inline abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/reference/ClassReference.java:22]: Same as for `ClassDependency` - added this to be able to define a direct reference to a class (as opposed to a field or method within a class)

File: abi-check-core/src/main/java/com/palantir/abi/checker/AbiCheckerClassLoader.java [hunk 3]
```diff
@@ -210,17 +207,39 @@ private static void analyseMethod(
...
+                AbstractInsnNode abstractInsnNode = method.instructions.get(labelNodeIndex + 1);
+                if (abstractInsnNode instanceof LineNumberNode lineNumberNode) {
+                    lineNumber = lineNumberNode.line;
+                }
+            }
+            caughtExceptions.add(CallSite.of(ClassReference.of(exception), lineNumber));
+        }
+
+        return caughtExceptions;
+    }
```
Comment (aldexis) [inline abi-check-core/src/main/java/com/palantir/abi/checker/AbiCheckerClassLoader.java:231]: This is similar to the below method, which finds exceptions caught when running a specific instruction, and instead returns all of the exceptions that are being caught, and the line where they are caught

File: abi-check-core/src/main/java/com/palantir/abi/checker/AbiCheckerClassLoader.java [hunk 4]
```diff
@@ -167,25 +167,19 @@ private static void analyseMethod(
                 }
                 if (insn instanceof MethodInsnNode methodInsn) {
                     handleMethodCall(
-                            methodCalls,
-                            lineNumber,
-                            methodInsn,
-                            () -> getCaughtExceptions(method.instructions, methodInsn, method));
+                            methodCalls, lineNumber, methodInsn, () -> getCaughtExceptions(method, methodInsn));
```
Comment (aldexis) [inline abi-check-core/src/main/java/com/palantir/abi/checker/AbiCheckerClassLoader.java:170]: Tiny drive-by refactor (no need to pass `method.instructions` when we already pass `method` anyway)

File: abi-check-core/src/test/java/com/palantir/abi/checker/integration/ClassConflictCheckerIntegrationTest.java [hunk 5]
```diff
@@ -74,47 +74,6 @@ public class RenamedClassWithAbiBreak {}
                 .withMessageContaining("com/ClassWithAbiBreak");
     }
 
-    @Test
-    public void try_catch_can_ignore_conflict() {
```
Comment (aldexis) [inline abi-check-core/src/test/java/com/palantir/abi/checker/integration/ClassConflictCheckerIntegrationTest.java:78]: Removed because it was duplicated by `catching_no_class_def_found_does_not_conflict` below

File: abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/conflict/ClassDependency.java [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/*
+ * Copyright (C) 2016 - 2025 Spotify AB
```
Comment (kunalrkak) [inline abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/conflict/ClassDependency.java]: Is this intentional? Also nit: 2026 on our license.

File: abi-check-core/src/test/java/com/palantir/abi/checker/integration/ClassConflictCheckerIntegrationTest.java [hunk 7]
```diff
@@ -191,4 +150,50 @@ public class Removed {}
 
         assertNoConflicts(tempDir);
     }
+
+    @Test
+    public void removed_caught_exception_creates_conflicts() {
```
Comment (kunalrkak) [inline abi-check-core/src/test/java/com/palantir/abi/checker/integration/ClassConflictCheckerIntegrationTest.java:158]: I didn't look through existing tests so some of these may already be covered, but can we test:
- catching an existing exception class doesn't fail
- multiple caught exceptions in one method works as intended
- conflicts aren't reported if target class is "ignored" (from [here](https://github.com/palantir/gradle-transitive-abi-checker/pull/312/changes#diff-f7148fbacc02306e4961103ba6df0f19886c6501e9842c0df437942ded9a1866R162))

File: abi-check-core/src/test/java/com/palantir/abi/checker/integration/BaseConflictCheckerIntegrationTest.java [hunk 8]
```diff
@@ -84,6 +85,8 @@ protected static JavaFileObject file(String className, String source) {
      * The class files will be copied in the provided directory, each under their respective subdirectory.
      */
     protected static void generateClassFiles(Path baseDir, JavaFiles sourceFiles) {
+        System.out.println("Generating class files to " + baseDir);
```
Comment (kunalrkak) [inline abi-check-core/src/test/java/com/palantir/abi/checker/integration/BaseConflictCheckerIntegrationTest.java:89]: Should this be logged instead of printing?

**Review by kunalrkak — DISMISSED** [review]
Few comments, nothing blocking. implementation looks good!

File: abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/conflict/ClassDependency.java (hunk 6 above)
Comment (aldexis) [reply abi-check-core/src/main/java/com/palantir/abi/checker/datamodel/conflict/ClassDependency.java]: It wasn't intentional, and instead due to copy-paste. Thanks for catching!

File: abi-check-core/src/test/java/com/palantir/abi/checker/integration/ClassConflictCheckerIntegrationTest.java (hunk 7 above)
Comment (aldexis) [reply abi-check-core/src/test/java/com/palantir/abi/checker/integration/ClassConflictCheckerIntegrationTest.java:158]: Re the first one, there are tests that test catching `NoClassDefFoundError` actually makes it ignore conflicts, and this actually broke when I had a bug in my logic, which I fixed by https://github.com/palantir/gradle-transitive-abi-checker/pull/312/changes/e59addbc26399188bb0b7321a0e5fedb4ac7c913

I'll write tests for the other two

File: abi-check-core/src/test/java/com/palantir/abi/checker/integration/BaseConflictCheckerIntegrationTest.java (hunk 8 above)
Comment (aldexis) [reply abi-check-core/src/test/java/com/palantir/abi/checker/integration/BaseConflictCheckerIntegrationTest.java:89]: I've had issues in the pass with logs not showing up at e.g. info. I'll see whether I can use logs here

Edit: actually, we don't even have a logging framework dependency here, so I'll just stick with the print statement

**Review by kunalrkak — APPROVED** [review]
Looks good, thanks!
